[package]
name = "class_attendance_contract"
version = "0.1.0"
edition = "2021"

[dependencies]
near-sdk = "4.0.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

[lib]
crate-type = ["cdylib"]
